### PR TITLE
Add in custom config creator

### PR DESCRIPTION
**Pull request by browniefed**

### CODE REVIEW

**Comment by browniefed** [comment]
@peterpme Haven't tested this. Plan to use this feature for white labeling expo apps.
So basically add ability to spin up a custom named config, rather than just prod/dev being created always.

**Comment by peterpme** [comment]
Hey @browniefed thanks for the PR! FWIW - You can do this with Expo's new release channels as well

Either way, if you test it and it works I'll merge it in

**Comment by browniefed** [comment]
I tested it and it did work, but don't worry about merging actually, just going to manage a local version for now.

I know you can use release channels but then that would also mean doing the copying of the `app.json` as you can't seemingly specify a different `app.json` when you do the build/publish.

Going to use a modified version of this and release channels to build a white labeled app.
Each release channel will be an app for a different customer then just use the `extra` field in the `app.json` to pump in the white labeled info.

**Comment by peterpme** [comment]
Ohhh ok cool. Are you sure? I really don't mind merging it in if it works, I'll just update the formatting

**Comment by browniefed** [comment]
It's up to you, going to be make modifications like release channel tagging and stuff so not sure if you depend on this package and how it operates for stuff at orchard

**Comment by peterpme** [comment]
We use release channels now so if you have a use-case for this I'd love to help

**Comment by browniefed** [comment]
Going to be doing more work on the flow today, did a lot of investigation yesterday so I'll let you know what I come up with.

**Comment by peterpme** [comment]
Awesome, excited to see what you come up with! I'm gonna run prettier on this & merge it in

**Comment by browniefed** [comment]
Did a bit more research for my use case and I think this will be fine as is. Might need addition of release channel tagging w/ deploys later but for now it's fine.

Was investigating using release channels as the white label solution. Then quickly realized that so much of the config is based on the app.json for deep linking, assets, etc. Release channels just aren't enough. Have to have separate apps entirely so the `exp-deploy-cli` works pretty alright for my use cases.

**Pull request merged**
